spring:
  profiles:
    active:
      - test
    group:
      local:
        - local
        - jwt
        - oauth
        - rabbitmq
        - firebase
      dev:
        - dev
        - jwt
        - oauth
        - rabbitmq
        - firebase
      test:
        - test
        - jwt
        - oauth
        - rabbitmq
        - firebase
      ops:
        - ops
        - jwt
        - oauth
        - rabbitmq
        - firebase