spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  profiles:
    active:
      - ops
    group:
      local:
        - local
        - jwt
        - oauth
        - rabbitmq
        - firebase
      dev:
        - dev
        - jwt
        - oauth
        - rabbitmq
        - firebase
      test:
        - test
        - jwt
        - oauth
        - rabbitmq
        - firebase
      ops:
        - ops
        - jwt
        - oauth
        - rabbitmq
        - firebase